[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-04-14 13:41:57,249][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[32mINFO[0m:     127.0.0.1:37628 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-04-14 13:41:57,252][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-04-14 13:41:57,265][flwr][DEBUG] - Opened insecure gRPC connection (no certificates were passed)
[2025-04-14 13:41:57,267][flwr][DEBUG] - ChannelConnectivity.IDLE
[2025-04-14 13:41:57,268][flwr][DEBUG] - ChannelConnectivity.CONNECTING
[2025-04-14 13:41:57,273][flwr][DEBUG] - ChannelConnectivity.TRANSIENT_FAILURE
[2025-04-14 13:41:57,476][flwr][DEBUG] - gRPC channel closed
[2025-04-14 13:41:57,477][root][INFO] - [E][PC0002] learning <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40025: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40025: Socket closed", grpc_status:14, created_time:"2025-04-14T13:41:57.273526941+09:00"}"
>
[2025-04-14 13:41:57,477][root][INFO] - notify_fail start
[2025-04-14 13:41:57,499][root][ERROR] - trainFin
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/responses.py", line 160, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/background.py", line 41, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/safer/FedOps/MNIST/app.py", line 211, in fl_client_start
    raise e
  File "/home/ccl/safer/FedOps/MNIST/app.py", line 174, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/flwr/client/app.py", line 731, in start_numpy_client
    start_client(
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/flwr/client/app.py", line 201, in start_client
    start_client_internal(
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/flwr/client/app.py", line 438, in start_client_internal
    message = receive()
              ^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/flwr/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40025: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40025: Socket closed", grpc_status:14, created_time:"2025-04-14T13:41:57.273526941+09:00"}"
>
[32mINFO[0m:     127.0.0.1:50782 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45554 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45560 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37954 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:42866 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:42878 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53348 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56138 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56140 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:41626 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58660 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58672 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:38884 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56448 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56452 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39998 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:38750 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:38760 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52856 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52862 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57462 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59620 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59624 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58566 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56404 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56420 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53470 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37102 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37110 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54948 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46952 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46954 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56156 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47324 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47326 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53408 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52894 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52910 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58012 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35276 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35284 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35716 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35720 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53800 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53170 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53176 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:48456 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52100 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52112 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47762 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45714 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45726 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57750 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39938 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39942 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53614 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47858 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47866 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46854 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44242 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44252 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40746 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40092 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40094 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56272 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56288 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45244 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57910 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57918 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:34046 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:43134 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:43136 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56564 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50860 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m1418058[0m]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb1d5578190>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8004): Max retries exceeded with url: /flclient_out (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb1d5578190>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccl/safer/FedOps/MNIST/client_main.py", line 78, in main
    fl_client.start()
  File "/home/ccl/safer/FedOps/MNIST/app.py", line 237, in start
    client_api.ClientMangerAPI().get_client_out()
  File "/home/ccl/safer/FedOps/MNIST/client_api.py", line 36, in get_client_out
    requests.get(self.client_manager_addr + '/flclient_out')
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8004): Max retries exceeded with url: /flclient_out (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb1d5578190>: Failed to establish a new connection: [Errno 111] Connection refused'))

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7fb1d5813060>
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/home/ccl/anaconda3/envs/fedops_hyp/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
